import { readFile, writeFile } from 'node:fs/promises';

const data = JSON.parse(await readFile(new URL('../src/tokens/buttons.json', import.meta.url), 'utf8'));
const resolve = (value) => value.replace(/\{([^}]+)\}/g, (_, key) => {
  if (!(key in data.primitives)) throw new Error(`Unknown token alias: ${key}`);
  return `var(--${key})`;
});
const declarations = (values) => Object.entries(values).map(([key, value]) => `  --${key}: ${resolve(value)};`).join('\n');
const css = [
  '/* Generated by npm run tokens. Edit src/tokens/buttons.json. */',
  `:root {\n${declarations(data.primitives)}\n}`,
  ...Object.entries(data.themes).map(([theme, values]) => `${theme === 'light' ? ':root, ' : ''}[data-theme="${theme}"] {\n${declarations(values)}\n}`),
].join('\n\n') + '\n';
await writeFile(new URL('../src/styles/tokens.css', import.meta.url), css);
