import fs from 'node:fs';
import { compileFigma } from './compile-figma.mjs';
const source = JSON.parse(fs.readFileSync('source/figma/fresh-export.json', 'utf8'));
const tokens = compileFigma(source);
fs.mkdirSync('src/tokens', { recursive: true });
fs.mkdirSync('src/styles', { recursive: true });
fs.writeFileSync('src/tokens/buttons.json', JSON.stringify(tokens, null, 2) + '\n');
const lines = ['/* Generated by npm run tokens from fresh Figma data. */'];
const variableById = new Map(tokens.usedVariables.map(v => [v.id, v]));
for (const theme of ['light', 'dark']) {
  const primary = tokens.records.find(r => r.theme === theme && r.variant === 'primary' && r.state === 'enable' && r.size === 32);
  const ghost = tokens.records.find(r => r.theme === theme && r.variant === 'ghost' && r.state === 'enable' && r.size === 32);
  lines.push('[data-theme="' + theme + '"] { --canvas: ' + tokens.surfaces[theme].color + '; --focus-accent: ' + primary.css.background + '; --demo-text: ' + ghost.css.color + '; }');
}
lines.push(':root {');
for (const v of tokens.usedVariables) lines.push('  ' + v.cssName + ': ' + v.nativeValue + 'px;');
lines.push('}');
const suffix = { enable: '', hover: ':hover:not(:disabled)', active: ':active:not(:disabled)', disable: ':disabled' };
// Disabled rules and active rules override base/hover irrespective of original layer order.
for (const state of ['enable', 'hover', 'active', 'disable']) for (const r of tokens.records.filter(row => row.state === state)) {
  lines.push('[data-theme="' + r.theme + '"] [data-button][data-variant="' + r.variant + '"][data-size="' + r.size + '"]' + suffix[state] + ' {');
  for (const [field, value] of Object.entries(r.css)) {
    let cssValue = value;
    if (r.bindings[field]) cssValue = 'var(' + variableById.get(r.bindings[field].id).cssName + ')';
    else if (typeof value === 'number' && !['opacity', 'textOpacity', 'fontWeight'].includes(field)) cssValue = value + 'px';
    else if (field === 'fontFamily') cssValue = '"' + value + '"';
    lines.push('  --button-' + field + ': ' + cssValue + ';');
  }
  lines.push('}');
}
fs.writeFileSync('src/styles/tokens.css', lines.join('\n') + '\n');
const light = tokens.schemas.light;
fs.writeFileSync('src/tokens/api.ts',
  '// Generated from Figma componentPropertyDefinitions.\n' +
  'export const variants = ' + JSON.stringify(light.type.variantOptions.map(v => v === 'ghost orange' ? 'ghost-orange' : v)) + ' as const;\n' +
  'export const sizes = ' + JSON.stringify(light.size.variantOptions.map(Number)) + ' as const;\n' +
  'export const defaults = ' + JSON.stringify({ variant: light.type.defaultValue, size: Number(light.size.defaultValue), icon: light[' icon #1900:0'].defaultValue, label: light['label#1918:0'].defaultValue }) + ' as const;\n');
console.log('Exported ' + tokens.records.length + ' states; ' + tokens.usedVariables.length + ' bound Figma variable; original schemas/modes/IDs preserved.');
const svg = fs.readFileSync('source/figma/light-icon-wrapper.svg', 'utf8');
const darkSvg = fs.readFileSync('source/figma/dark-icon-wrapper.svg', 'utf8');
const path = svg.match(/<path d="([^"]+)"/)?.[1];
if (!path || path !== darkSvg.match(/<path d="([^"]+)"/)?.[1]) throw new Error('Icon geometry differs between themes');
fs.mkdirSync('src/assets', { recursive: true });
fs.writeFileSync('src/assets/AddIcon.tsx',
  '// Generated from the actual Figma wrapper SVG. Color follows verified label paints.\n' +
  'export function AddIcon() { return <svg width="16" height="16" viewBox="0 0 16 16" aria-hidden="true" focusable="false"><path d=' + JSON.stringify(path) + ' fill="currentColor" /></svg>; }\n');
